import { BedDouble, DoorOpen, ImagePlus, Pencil, Plus, Trash2, UserPlus, X } from "lucide-react";
import { FormEvent, type ReactNode, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { BuildingEmptyState, LoadingState } from "@/components/AppStates";
import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { formatCurrency, toPaise } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { useActiveBuilding } from "@/hooks/useActiveBuilding";
import { useDeletionSafety } from "@/components/DeletionSafety";
import { UploadProgress } from "@/components/UploadProgress";
import { useUploadFeedback } from "@/hooks/useUploadFeedback";

const fieldClass = "h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";
const capacityForRoomType = { single: 1, double: 2, triple: 3, four: 4, individual: 2, coliving: 2 } as const;
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-medium"><span className="mb-1.5 block">{label}</span>{children}</label>; }

function fileToDataUrl(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("The image could not be read."));
    reader.onload = () => typeof reader.result === "string" ? resolve(reader.result) : reject(new Error("The image could not be read."));
    reader.readAsDataURL(file);
  });
}

export default function Rooms() {
  const { buildingsQuery, building, buildingId, setBuildingId, snapshotQuery: snapshot } = useActiveBuilding();
  const utils = trpc.useUtils();
  const { requestDelete } = useDeletionSafety();
  const [showFloor, setShowFloor] = useState(false);
  const [showRoom, setShowRoom] = useState(false);
  const [showRoomSetup, setShowRoomSetup] = useState(false);
  const [editingRoomId, setEditingRoomId] = useState<number | null>(null);
  const [allocatingRoomId, setAllocatingRoomId] = useState<number | null>(null);
  const [creatingTenantInRoomId, setCreatingTenantInRoomId] = useState<number | null>(null);
  const [vacantOnly, setVacantOnly] = useState(false);
  const uploadFeedback = useUploadFeedback();
  const generateFloors = trpc.pg.operations.addGeneratedFloors.useMutation({ onSuccess: async result => { await utils.pg.operations.snapshot.invalidate(); setShowFloor(false); toast.success(result.createdCount > 0 ? `${result.createdCount} floor${result.createdCount === 1 ? "" : "s"} created` : "These standard floors already exist"); }, onError: error => toast.error(error.message) });
  const deleteFloor = trpc.pg.operations.deleteFloor.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); toast.success("Floor deleted"); }, onError: error => toast.error(error.message) });
  const addRoom = trpc.pg.operations.addRoom.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); setShowRoom(false); uploadFeedback.clear(); toast.success("Room added"); }, onError: error => { uploadFeedback.clear(); toast.error(error.message); } });
  const setupRoomWithTenant = trpc.pg.operations.setupRoomWithTenant.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); setShowRoomSetup(false); uploadFeedback.clear(); toast.success("Room, tenant, rent, and services saved"); }, onError: error => { uploadFeedback.clear(); toast.error(error.message); } });
  const updateRoom = trpc.pg.operations.updateRoom.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); setEditingRoomId(null); uploadFeedback.clear(); toast.success("Room details updated"); }, onError: error => { uploadFeedback.clear(); toast.error(error.message); } });
  const allocateTenantWithServices = trpc.pg.operations.allocateTenantWithServices.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); setAllocatingRoomId(null); toast.success("Tenant, rent, and services saved for this room"); }, onError: error => toast.error(error.message) });
  const createTenantForRoom = trpc.pg.operations.createTenantForRoom.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); setCreatingTenantInRoomId(null); toast.success("New tenant, rent, allocation, and services saved for this room"); }, onError: error => toast.error(error.message) });
  const deleteRoom = trpc.pg.operations.deleteRoom.useMutation({ onSuccess: async () => { await utils.pg.operations.snapshot.invalidate(); toast.success("Room deleted"); }, onError: error => toast.error(error.message) });
  const uploadImage = trpc.pg.uploads.image.useMutation({ onError: error => { uploadFeedback.clear(); toast.error(error.message); } });
  const roomOccupancy = useMemo(() => { const counts = new Map<number, number>(); snapshot.data?.allocations.filter(item => item.status === "active").forEach(item => counts.set(item.roomId, (counts.get(item.roomId) ?? 0) + 1)); return counts; }, [snapshot.data]);
  const requestedAllocationRoomId = Number(new URLSearchParams(window.location.search).get("allocate"));
  useEffect(() => {
    if (!Number.isSafeInteger(requestedAllocationRoomId) || requestedAllocationRoomId < 1 || !snapshot.data) return;
    const room = snapshot.data.rooms.find(item => item.id === requestedAllocationRoomId);
    if (room && (roomOccupancy.get(room.id) ?? 0) < room.capacity) setAllocatingRoomId(room.id);
  }, [requestedAllocationRoomId, roomOccupancy, snapshot.data]);
  const visibleRooms = useMemo(() => snapshot.data?.rooms.filter(room => !vacantOnly || (roomOccupancy.get(room.id) ?? 0) < room.capacity) ?? [], [roomOccupancy, snapshot.data, vacantOnly]);
  const unallocatedActiveTenants = useMemo(() => snapshot.data?.tenants.filter(tenant => tenant.status === "active" && !snapshot.data?.allocations.some(allocation => allocation.tenantId === tenant.id && allocation.status === "active")) ?? [], [snapshot.data]);

  if (buildingsQuery.isLoading) return <LoadingState />;
  if (!building || !buildingId) return <BuildingEmptyState />;
  if (snapshot.isLoading || !snapshot.data) return <LoadingState />;

  const orderedFloors = snapshot.data.floors.slice().sort((a, b) => a.level - b.level);
  const uploadFromForm = async (form: FormData, purpose: "room") => {
    const image = form.get("image");
    if (!(image instanceof File) || image.size === 0) return String(form.get("imageUrl") ?? "").trim();
    const uploaded = await uploadFeedback.uploadFile(image, dataUrl => uploadImage.mutateAsync({ dataUrl, purpose }));
    return uploaded.url;
  };
  const submitFloor = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); generateFloors.mutate({ buildingId, floorCount: Number(form.get("floorCount")) }); };
  const submitRoom = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    try {
      const imageUrl = await uploadFromForm(form, "room");
      const roomType = String(form.get("roomType")) as keyof typeof capacityForRoomType;
      uploadFeedback.markSaving();
      await addRoom.mutateAsync({ buildingId, floorId: form.get("floorId") ? Number(form.get("floorId")) : null, number: String(form.get("number")), capacity: roomType === "individual" ? Number(form.get("capacity") || 2) : capacityForRoomType[roomType], roomType, billingMode: String(form.get("billingMode")) as "equal_split" | "manager_set" | "primary_payer", airConditioning: String(form.get("airConditioning")) as "ac" | "non_ac", balcony: String(form.get("balcony")) as "balcony" | "non_balcony", imageUrl, defaultRentPaise: toPaise(String(form.get("defaultRent")) || "0") });
    } catch (error) { uploadFeedback.clear(); toast.error(error instanceof Error ? error.message : "Room image could not be uploaded."); }
  };
  const submitRoomUpdate = async (event: FormEvent<HTMLFormElement>, roomId: number) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    try {
      const imageUrl = await uploadFromForm(form, "room");
      const roomType = String(form.get("roomType")) as keyof typeof capacityForRoomType;
      uploadFeedback.markSaving();
      await updateRoom.mutateAsync({ id: roomId, buildingId, floorId: form.get("floorId") ? Number(form.get("floorId")) : null, number: String(form.get("number")), capacity: roomType === "individual" ? Number(form.get("capacity") || 2) : capacityForRoomType[roomType], roomType, billingMode: String(form.get("billingMode")) as "equal_split" | "manager_set" | "primary_payer", airConditioning: String(form.get("airConditioning")) as "ac" | "non_ac", balcony: String(form.get("balcony")) as "balcony" | "non_balcony", imageUrl, defaultRentPaise: toPaise(String(form.get("defaultRent")) || "0") });
    } catch (error) { uploadFeedback.clear(); toast.error(error instanceof Error ? error.message : "Room image could not be uploaded."); }
  };
  const optionalServicesFromForm = (form: FormData) => {
    const services: Array<{ serviceType: "tiffin" | "water_bottle" | "other"; monthlyChargePaise: number; notes?: string }> = [];
    const addService = (serviceType: "tiffin" | "water_bottle" | "other", chargeField: string, notes?: string) => { const monthlyChargePaise = toPaise(String(form.get(chargeField)) || "0"); if (monthlyChargePaise > 0) services.push({ serviceType, monthlyChargePaise, notes }); };
    addService("tiffin", "tiffinCharge", "Tiffin service");
    addService("water_bottle", "waterCharge", "Water bottle service");
    addService("other", "otherServiceCharge", String(form.get("otherServiceName")) || undefined);
    return services;
  };
  const submitRoomSetup = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    try {
      const imageUrl = await uploadFromForm(form, "room");
      const roomType = String(form.get("roomType")) as keyof typeof capacityForRoomType;
      uploadFeedback.markSaving();
      await setupRoomWithTenant.mutateAsync({ buildingId, floorId: form.get("floorId") ? Number(form.get("floorId")) : null, number: String(form.get("number")), capacity: roomType === "individual" ? Number(form.get("capacity") || 2) : capacityForRoomType[roomType], roomType, billingMode: String(form.get("billingMode")) as "equal_split" | "manager_set" | "primary_payer", airConditioning: String(form.get("airConditioning")) as "ac" | "non_ac", balcony: String(form.get("balcony")) as "balcony" | "non_balcony", imageUrl, defaultRentPaise: toPaise(String(form.get("defaultRent")) || "0"), tenant: { fullName: String(form.get("tenantFullName")), phone: String(form.get("tenantPhone")), password: String(form.get("tenantPassword")), email: String(form.get("tenantEmail")) || "", emergencyContactName: String(form.get("tenantEmergencyName")) || undefined, emergencyContactPhone: String(form.get("tenantEmergencyPhone")) || undefined, address: String(form.get("tenantAddress")) || undefined, identityDocumentUrl: String(form.get("tenantIdentityDocumentUrl")) || "" }, allocation: { moveInDate: String(form.get("moveInDate")), bedLabel: String(form.get("bedLabel")) || undefined, monthlyRentPaise: toPaise(String(form.get("monthlyRent")) || "0"), depositPaise: toPaise(String(form.get("deposit"))), isPrimaryPayer: "yes" }, services: optionalServicesFromForm(form) });
    } catch (error) { uploadFeedback.clear(); toast.error(error instanceof Error ? error.message : "Room setup image could not be uploaded."); }
  };
  const requestRoomDeletion = (roomId: number, roomNumber: string) => { if (!deleteRoom.isPending) requestDelete({ label: `Room ${roomNumber}`, description: "Rooms with tenant allocations or electricity history are protected. Only an unused room can be removed.", onConfirm: () => deleteRoom.mutate({ id: roomId, buildingId }) }); };
  const requestFloorDeletion = (floorId: number, floorName: string) => { if (!deleteFloor.isPending) requestDelete({ label: floorName, description: "Floors with assigned rooms are protected. Only an empty floor can be removed.", onConfirm: () => deleteFloor.mutate({ id: floorId, buildingId }) }); };

  const roomFields = (room?: typeof snapshot.data.rooms[number], includeDefaultRent = true) => <>
    <Field label="Floor"><select name="floorId" defaultValue={room?.floorId ?? ""} className={fieldClass}><option value="">No floor</option>{orderedFloors.map(floor => <option key={floor.id} value={floor.id}>{floor.name} (Level {floor.level})</option>)}</select></Field>
    <Field label="Room number"><input required name="number" defaultValue={room?.number} className={fieldClass} placeholder="101" /></Field>
    <Field label="Room type"><select name="roomType" defaultValue={room?.roomType ?? "single"} className={fieldClass}><option value="single">Single</option><option value="double">Double sharing</option><option value="triple">Triple sharing</option><option value="four">Four sharing</option><option value="individual">Individual room (multi-tenant)</option><option value="coliving">Co-living room (couple)</option></select></Field>
    <Field label="Billing allocation"><select name="billingMode" defaultValue={room?.billingMode ?? "equal_split"} className={fieldClass}><option value="equal_split">Equal split between active tenants</option><option value="manager_set">Manager sets charges manually</option><option value="primary_payer">Primary tenant pays all room bills</option></select></Field>
    <Field label="Cooling"><select name="airConditioning" defaultValue={room?.airConditioning ?? "non_ac"} className={fieldClass}><option value="non_ac">Non-AC</option><option value="ac">AC</option></select></Field>
    <Field label="View"><select name="balcony" defaultValue={room?.balcony ?? "non_balcony"} className={fieldClass}><option value="non_balcony">Non-balcony</option><option value="balcony">Balcony</option></select></Field>
    <Field label="Individual-room maximum tenants"><input name="capacity" type="number" min="2" max="12" defaultValue={room?.roomType === "individual" ? room.capacity : 2} className={fieldClass} /><span className="mt-1 block text-xs text-muted-foreground">Used only for Individual rooms. Other types set capacity automatically.</span></Field>
    <div className="rounded-xl border border-primary/15 bg-primary/[0.035] px-3 py-2.5 text-xs leading-5 text-muted-foreground">Standard sharing rooms split electricity and room-shared costs equally. Individual rooms only create tenant dues when the Manager sets them. Co-living rooms assign rent and shared bills to one primary tenant.</div>
    {includeDefaultRent ? <Field label="Default room rent (₹)"><input name="defaultRent" inputMode="decimal" defaultValue={room ? room.defaultRentPaise / 100 : "0"} className={fieldClass} /></Field> : null}
    {room ? <p className="text-xs leading-5 text-muted-foreground">For standard sharing rooms, the displayed total comes from active tenant rents. Individual rooms retain the Manager-set room reference rent until tenant charges are configured.</p> : null}
    <Field label="Room photo URL"><input name="imageUrl" type="url" defaultValue={room?.imageUrl ?? ""} className={fieldClass} placeholder="https://…" /></Field>
    <Field label="Or upload room photo"><input name="image" type="file" accept="image/jpeg,image/png,image/webp" className="block h-11 w-full cursor-pointer rounded-xl border border-border bg-background px-3 py-2 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-primary/10 file:px-2 file:py-1 file:text-xs file:font-semibold file:text-primary" /></Field>
  </>;
  const newTenantFields = () => <><div className="sm:col-span-2 mt-2 border-t border-primary/15 pt-4"><p className="text-sm font-semibold">First tenant and login</p><p className="mt-1 text-xs text-muted-foreground">This creates a phone-password tenant login and assigns the resident to the room immediately.</p></div><Field label="Tenant full name"><input required name="tenantFullName" className={fieldClass} /></Field><Field label="Tenant mobile number"><input required name="tenantPhone" inputMode="tel" className={fieldClass} /></Field><Field label="Tenant login password"><input required name="tenantPassword" type="password" minLength={8} className={fieldClass} /></Field><Field label="Tenant email"><input name="tenantEmail" type="email" className={fieldClass} /></Field><Field label="Emergency contact name"><input name="tenantEmergencyName" className={fieldClass} /></Field><Field label="Emergency contact number"><input name="tenantEmergencyPhone" inputMode="tel" className={fieldClass} /></Field><Field label="Home address"><input name="tenantAddress" className={fieldClass} /></Field><Field label="Identity document URL"><input name="tenantIdentityDocumentUrl" type="url" className={fieldClass} placeholder="https://…" /></Field><Field label="Move-in date"><input required name="moveInDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className={fieldClass} /></Field><Field label="Bed label"><input name="bedLabel" className={fieldClass} placeholder="A, lower, window" /></Field><Field label="Agreed monthly rent (₹)"><input required name="monthlyRent" inputMode="decimal" className={fieldClass} /></Field><Field label="Security deposit (₹)"><input required name="deposit" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field></>;
  const optionalServiceFields = () => <><div className="sm:col-span-2 mt-2 rounded-2xl border border-emerald-200 bg-emerald-50/60 p-3"><p className="text-xs font-semibold text-emerald-900">Optional monthly services</p><p className="mt-1 text-xs leading-5 text-emerald-800">Enter a charge only for services this tenant uses. Leave a charge at ₹0 to skip it.</p></div><Field label="Tiffin monthly charge (₹)"><input name="tiffinCharge" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field><Field label="Water bottle monthly charge (₹)"><input name="waterCharge" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field><Field label="Other service name"><input name="otherServiceName" className={fieldClass} placeholder="Laundry, Wi-Fi, etc." /></Field><Field label="Other service monthly charge (₹)"><input name="otherServiceCharge" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field></>;

  return <div className="pb-8"><PageHeader eyebrow="Property" title="Floors & rooms" description="Configure every floor and bed in the building. Use guided setup to create a room and first tenant together." buildings={buildingsQuery.data} buildingId={buildingId} onBuildingChange={setBuildingId} actions={<><button type="button" onClick={() => setShowFloor(value => !value)} className="h-11 rounded-xl border border-border bg-card px-3 text-sm font-semibold text-foreground transition hover:bg-muted">Generate floors</button><button type="button" onClick={() => setShowRoomSetup(value => !value)} className="h-11 rounded-xl border border-primary/25 bg-primary/[0.04] px-3 text-sm font-semibold text-primary"><UserPlus className="mr-1.5 inline h-4 w-4" />Guided setup</button><PrimaryAction onClick={() => setShowRoom(value => !value)}><Plus className="mr-1.5 h-4 w-4" />Add room</PrimaryAction></>} />
    {showFloor ? <form onSubmit={submitFloor} className="mb-5 grid gap-3 rounded-3xl border border-primary/20 bg-primary/[0.035] p-4 sm:grid-cols-3 sm:p-5"><div className="sm:col-span-3 rounded-2xl border border-primary/15 bg-card/70 p-3 text-xs leading-5 text-muted-foreground"><p className="font-semibold text-foreground">Generate standard floors</p><p className="mt-1">Enter the number of numbered floors. For example, <span className="font-semibold text-foreground">3</span> creates Ground Floor, Floor 1, Floor 2, Floor 3, and Terrace.</p></div><Field label="Number of floors"><input required name="floorCount" type="number" min="0" max="200" step="1" defaultValue="1" inputMode="numeric" className={fieldClass} /></Field><div className="flex items-end sm:col-span-2"><button type="submit" disabled={generateFloors.isPending} className="h-11 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60">{generateFloors.isPending ? "Generating floors…" : "Generate floors"}</button></div></form> : null}
    {showRoom ? <form onSubmit={submitRoom} className="mb-5 grid gap-3 rounded-3xl border border-primary/20 bg-primary/[0.035] p-4 sm:grid-cols-2 sm:p-5">{roomFields()}<div className="sm:col-span-2">{uploadFeedback.state ? <UploadProgress {...uploadFeedback.state} onCancel={uploadFeedback.cancel} onRetry={() => void uploadFeedback.retry()} onDismiss={uploadFeedback.clear} /> : null}</div><div className="sm:col-span-2 flex flex-wrap gap-2"><button type="submit" disabled={addRoom.isPending || uploadImage.isPending} className="inline-flex h-11 items-center justify-center rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60">{addRoom.isPending || uploadImage.isPending || uploadFeedback.state ? "Saving…" : "Add room"}</button><button type="button" onClick={() => setShowRoom(false)} className="h-11 rounded-xl border border-border bg-card px-4 text-sm font-semibold">Cancel</button></div></form> : null}
    {showRoomSetup ? <form onSubmit={submitRoomSetup} className="mb-5 grid gap-3 rounded-3xl border border-primary/25 bg-primary/[0.035] p-4 sm:grid-cols-2 sm:p-5"><div className="sm:col-span-2 rounded-2xl border border-primary/15 bg-card/70 p-3 text-xs leading-5 text-muted-foreground">Guided setup creates the room, the first tenant’s phone-password login, their allocation, agreed rent, current-month rent cycle, and any selected services together. For shared rooms, add additional residents from the room card afterward.</div>{roomFields(undefined, false)}{newTenantFields()}{optionalServiceFields()}<div className="sm:col-span-2">{uploadFeedback.state ? <UploadProgress {...uploadFeedback.state} onCancel={uploadFeedback.cancel} onRetry={() => void uploadFeedback.retry()} onDismiss={uploadFeedback.clear} /> : null}</div><div className="sm:col-span-2 flex flex-wrap gap-2"><button type="submit" disabled={setupRoomWithTenant.isPending || uploadImage.isPending} className="inline-flex h-11 items-center justify-center rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60">{setupRoomWithTenant.isPending || uploadImage.isPending || uploadFeedback.state ? "Saving setup…" : "Create room & tenant"}</button><button type="button" onClick={() => setShowRoomSetup(false)} className="h-11 rounded-xl border border-border bg-card px-4 text-sm font-semibold">Cancel</button></div></form> : null}
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{orderedFloors.length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-muted/30 p-4 text-sm text-muted-foreground">No floors configured. Rooms can still be added without a floor.</div> : orderedFloors.map(floor => <article key={floor.id} className="flex items-center justify-between rounded-2xl border border-border/70 bg-card px-4 py-3"><div><p className="text-sm font-semibold">{floor.name}</p><p className="text-xs text-muted-foreground">Level {floor.level} · {snapshot.data.rooms.filter(room => room.floorId === floor.id).length} rooms</p></div><button onClick={() => requestFloorDeletion(floor.id, floor.name)} className="grid h-10 w-10 place-items-center rounded-xl border border-rose-200 text-rose-600 transition hover:bg-rose-50" aria-label={`Delete ${floor.name}`}><Trash2 className="h-4 w-4" /></button></article>)}</section>
    <section className="mb-4 rounded-2xl border border-border/70 bg-card p-3 shadow-[0_8px_20px_rgba(23,43,77,0.04)]"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">Room availability</p><p className="text-xs text-muted-foreground">{visibleRooms.length} of {snapshot.data.rooms.length} room{snapshot.data.rooms.length === 1 ? "" : "s"} shown</p></div><button type="button" onClick={() => setVacantOnly(value => !value)} aria-pressed={vacantOnly} className={`h-10 rounded-xl px-3 text-sm font-semibold transition ${vacantOnly ? "bg-primary text-primary-foreground" : "border border-border bg-background text-foreground hover:bg-muted"}`}>{vacantOnly ? "Vacant Only: On" : "Vacant Only"}</button></div></section>
    <section className="motion-stagger grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      {snapshot.data.rooms.length === 0 ? <div className="sm:col-span-2 xl:col-span-3 rounded-3xl border border-dashed border-border bg-muted/30 p-8 text-center"><DoorOpen className="mx-auto h-6 w-6 text-primary" /><p className="mt-3 font-semibold">No rooms configured yet</p><p className="mt-1 text-sm text-muted-foreground">Add floors and rooms to start allocating tenants and tracking billing.</p></div> : visibleRooms.length === 0 ? <div className="sm:col-span-2 xl:col-span-3 rounded-3xl border border-dashed border-border bg-muted/30 p-8 text-center"><DoorOpen className="mx-auto h-6 w-6 text-primary" /><p className="mt-3 font-semibold">No rooms with open beds</p><p className="mt-1 text-sm text-muted-foreground">Turn off Vacant Only to review full rooms.</p></div> : visibleRooms.map(room => {
        const occupied = roomOccupancy.get(room.id) ?? 0;
        const floor = snapshot.data.floors.find(item => item.id === room.floorId);
        const isOccupied = occupied > 0;
        const isFull = occupied >= room.capacity;
        const isEditing = editingRoomId === room.id;
        const isAllocating = allocatingRoomId === room.id;
        const isCreatingTenant = creatingTenantInRoomId === room.id;
        const availableBeds = Math.max(room.capacity - occupied, 0);
        const occupancyPercent = Math.min(Math.round((occupied / room.capacity) * 100), 100);
        const roomTypeLabel = room.roomType === "four" ? "Four sharing" : room.roomType === "individual" ? "Individual room" : room.roomType === "coliving" ? "Co-living room" : `${room.roomType[0].toUpperCase()}${room.roomType.slice(1)}${room.roomType === "single" ? "" : " sharing"}`;
        return <article key={room.id} className={`overflow-hidden rounded-3xl border shadow-[0_10px_28px_rgba(23,43,77,0.05)] ${isOccupied ? "border-primary/20 bg-primary/[0.03]" : "border-border/70 bg-card"}`}>
          {room.imageUrl ? <img src={room.imageUrl} alt={`Room ${room.number}`} className="h-36 w-full object-cover" /> : <div className="grid h-28 place-items-center bg-muted/50 text-muted-foreground"><ImagePlus className="h-6 w-6" /></div>}
          <div className="p-4 sm:p-5">
            <div className="flex items-start justify-between gap-3"><div><div className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10"><DoorOpen className="h-5 w-5 text-primary" /></div><h2 className="mt-3 text-base font-semibold">Room {room.number}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${isFull ? "bg-amber-100 text-amber-800" : isOccupied ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>{isFull ? "Full" : isOccupied ? "Occupied" : "Vacant"}</span></div>
            <p className="mt-1 text-sm text-muted-foreground">{roomTypeLabel} · {room.airConditioning === "ac" ? "AC" : "Non-AC"} · {room.balcony === "balcony" ? "Balcony" : "Non-balcony"}</p><p className="mt-1 text-xs text-muted-foreground">{floor ? floor.name : "No floor"}</p>
            <div className="mt-4 rounded-2xl border border-primary/10 bg-primary/[0.035] p-3"><div className="flex items-center justify-between gap-3 text-xs"><span className="flex items-center gap-1.5 font-semibold text-foreground"><BedDouble className="h-3.5 w-3.5 text-primary" />{occupied}/{room.capacity} beds filled</span><span className={availableBeds === 0 ? "font-semibold text-amber-800" : "text-muted-foreground"}>{availableBeds === 0 ? "No beds open" : `${availableBeds} bed${availableBeds === 1 ? "" : "s"} open`}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-primary/10" aria-label={`${occupied} of ${room.capacity} beds filled`}><div className={`h-full rounded-full ${isFull ? "bg-amber-500" : "bg-primary"}`} style={{ width: `${occupancyPercent}%` }} /></div></div>
            <div className="mt-3 flex items-center justify-between rounded-2xl bg-muted/60 px-3 py-2 text-xs"><span className="text-muted-foreground">Current room rent total</span><span className="font-semibold">{room.defaultRentPaise > 0 ? formatCurrency(room.defaultRentPaise) : "—"}</span></div>
            {isEditing ? <><form onSubmit={event => submitRoomUpdate(event, room.id)} className="mt-4 grid gap-3 border-t border-border/70 pt-4 sm:grid-cols-2">{roomFields(room)}<div className="sm:col-span-2 flex flex-wrap gap-2"><button type="submit" disabled={updateRoom.isPending || uploadImage.isPending} className="inline-flex h-11 items-center justify-center rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60">{updateRoom.isPending || uploadImage.isPending ? "Saving…" : "Save room"}</button><button type="button" onClick={() => setEditingRoomId(null)} className="inline-flex h-11 items-center gap-1.5 rounded-xl border border-border bg-card px-4 text-sm font-semibold"><X className="h-4 w-4" />Cancel</button></div></form>{!isFull ? <button type="button" onClick={() => setAllocatingRoomId(value => value === room.id ? null : room.id)} className="mt-3 inline-flex h-10 items-center gap-1.5 rounded-xl border border-primary/25 bg-primary/[0.04] px-3 text-sm font-semibold text-primary"><BedDouble className="h-4 w-4" />Allocate tenant</button> : null}</> : <div className="mt-4 flex flex-wrap gap-2">{!isFull ? <button type="button" onClick={() => setAllocatingRoomId(value => value === room.id ? null : room.id)} className="flex h-11 flex-1 items-center justify-center gap-1.5 rounded-xl border border-primary/25 bg-primary/[0.04] text-sm font-semibold text-primary"><BedDouble className="h-4 w-4" />Allocate tenant</button> : null}<button onClick={() => setEditingRoomId(room.id)} className="flex h-11 flex-1 items-center justify-center gap-1.5 rounded-xl border border-border bg-card px-3 text-sm font-semibold text-foreground transition hover:bg-muted"><Pencil className="h-4 w-4" />Edit room</button><button onClick={() => requestRoomDeletion(room.id, room.number)} className="grid h-11 w-11 place-items-center rounded-xl border border-rose-200 text-rose-600 transition hover:bg-rose-50" aria-label={`Delete Room ${room.number}`}><Trash2 className="h-4 w-4" /></button></div>}
            {isAllocating ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); allocateTenantWithServices.mutate({ buildingId, roomId: room.id, tenantId: Number(form.get("tenantId")), moveInDate: String(form.get("moveInDate")), bedLabel: String(form.get("bedLabel")) || undefined, isPrimaryPayer: String(form.get("isPrimaryPayer")) as "no" | "yes", monthlyRentPaise: toPaise(String(form.get("monthlyRent")) || "0"), depositPaise: toPaise(String(form.get("deposit"))), services: optionalServicesFromForm(form) }); }} className="mt-4 grid gap-3 rounded-2xl border border-primary/20 bg-primary/[0.035] p-3 sm:grid-cols-2"><div className="sm:col-span-2"><p className="text-sm font-semibold">Allocate a tenant to Room {room.number}</p><p className="mt-1 text-xs text-muted-foreground">Set rent only when this tenant is liable. In Co-living, one primary payer is liable for the room’s rent and shared bills.</p></div><Field label="Tenant"><select required name="tenantId" className={fieldClass}><option value="">Choose unallocated tenant</option>{unallocatedActiveTenants.map(tenant => <option key={tenant.id} value={tenant.id}>{tenant.fullName}</option>)}</select></Field><Field label="Move-in date"><input required name="moveInDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className={fieldClass} /></Field><Field label="Bed label"><input name="bedLabel" className={fieldClass} placeholder="A, lower, window" /></Field><Field label="Co-living primary payer"><select name="isPrimaryPayer" defaultValue="no" className={fieldClass}><option value="no">No</option><option value="yes">Yes — pays room bills</option></select></Field><Field label="Agreed monthly rent (₹)"><input required name="monthlyRent" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field><Field label="Security deposit (₹)"><input required name="deposit" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field>{optionalServiceFields()}<div className="sm:col-span-2 flex gap-2"><button type="submit" disabled={allocateTenantWithServices.isPending || unallocatedActiveTenants.length === 0} className="h-10 rounded-xl bg-primary px-3 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">{allocateTenantWithServices.isPending ? "Allocating…" : "Save tenant allocation"}</button><button type="button" onClick={() => setAllocatingRoomId(null)} className="h-10 rounded-xl border border-border bg-card px-3 text-sm font-semibold">Cancel</button></div></form> : null}
          </div>
          {!isFull ? <div className="border-t border-border/70 px-4 py-3 sm:px-5"><button type="button" onClick={() => setCreatingTenantInRoomId(value => value === room.id ? null : room.id)} className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-primary/25 bg-primary/[0.04] px-3 text-xs font-semibold text-primary"><UserPlus className="h-3.5 w-3.5" />Create new tenant for this room</button></div> : null}
          {isCreatingTenant ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createTenantForRoom.mutate({ buildingId, roomId: room.id, tenant: { fullName: String(form.get("tenantFullName")), phone: String(form.get("tenantPhone")), password: String(form.get("tenantPassword")), email: String(form.get("tenantEmail")) || "", emergencyContactName: String(form.get("tenantEmergencyName")) || undefined, emergencyContactPhone: String(form.get("tenantEmergencyPhone")) || undefined, address: String(form.get("tenantAddress")) || undefined, identityDocumentUrl: String(form.get("tenantIdentityDocumentUrl")) || "" }, allocation: { moveInDate: String(form.get("moveInDate")), bedLabel: String(form.get("bedLabel")) || undefined, monthlyRentPaise: toPaise(String(form.get("monthlyRent"))), depositPaise: toPaise(String(form.get("deposit"))) }, services: optionalServicesFromForm(form) }); }} className="m-4 grid gap-3 rounded-2xl border border-primary/25 bg-primary/[0.035] p-3 sm:m-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="text-sm font-semibold">Create a new tenant for Room {room.number}</p><p className="mt-1 text-xs text-muted-foreground">Create the phone-password login, allocation, agreed rent, and optional services in one step.</p></div>{newTenantFields()}{optionalServiceFields()}<div className="sm:col-span-2 flex gap-2"><button type="submit" disabled={createTenantForRoom.isPending} className="h-10 rounded-xl bg-primary px-3 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">{createTenantForRoom.isPending ? "Saving…" : "Create tenant & allocate"}</button><button type="button" onClick={() => setCreatingTenantInRoomId(null)} className="h-10 rounded-xl border border-border bg-card px-3 text-sm font-semibold">Cancel</button></div></form> : null}
        </article>;
      })}
    </section>
  </div>;
}
