import { type FormEvent } from "react";
import { BellRing, LayoutList, Settings2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { BuildingEmptyState, LoadingState } from "@/components/AppStates";
import { MotionPreferencePanel } from "@/components/MotionPreferencePanel";
import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { formatCurrency, toPaise } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { useActiveBuilding } from "@/hooks/useActiveBuilding";
import { useAuth } from "@/_core/hooks/useAuth";
import { useMotionPreferences } from "@/contexts/MotionContext";

const fieldClass = "h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium"><span className="mb-1.5 block">{label}</span>{children}</label>; }

const roles = [
  ["Owner", "Full access to every assigned building, report, and personal setting."],
  ["Manager", "Operational access across assigned buildings, including billing, expenses, reminders, exports, and settings."],
  ["Tenant", "Can view an active room, allocated bills, payment instructions, and submit payment receipts or support requests."],
  ["Staff costs", "Helper, cook, and vendor work are tracked in the Manager operating-cost ledger; they do not receive staff login accounts."],
];

export default function Settings() {
  const { user } = useAuth();
  const { buildingsQuery, building, buildingId, setBuildingId } = useActiveBuilding();
  const utils = trpc.useUtils();
  const { displayDensity, setDisplayDensity } = useMotionPreferences();
  const update = trpc.pg.buildings.update.useMutation({ onSuccess: async () => { await utils.pg.buildings.list.invalidate(); toast.success("Building settings saved"); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin" && user?.role !== "manager") return <div className="mx-auto max-w-xl rounded-3xl border border-border/70 bg-card p-8 text-center shadow-[0_10px_28px_rgba(23,43,77,0.05)]"><ShieldCheck className="mx-auto h-6 w-6 text-primary" /><h1 className="mt-4 text-lg font-semibold">Manager or Owner access required</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Building configuration is available to the Owner and delegated Manager. Team membership and role administration remain Owner-only.</p></div>;
  if (buildingsQuery.isLoading) return <LoadingState />;
  if (!building || !buildingId) return <BuildingEmptyState />;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ id: buildingId, name: String(form.get("name")), address: String(form.get("address")), city: String(form.get("city")) || null, landmark: String(form.get("landmark")) || null, contactPhone: String(form.get("contactPhone")) || null, imageUrl: String(form.get("imageUrl")) || null, mapUrl: String(form.get("mapUrl")) || null, ownerMonthlyCutPaise: toPaise(String(form.get("ownerMonthlyCut"))), electricityRatePaise: toPaise(String(form.get("rate"))), rentDueDay: Number(form.get("rentDueDay") || 5) }); };

  return <div className="pb-8"><PageHeader eyebrow="Configuration" title="Settings" description="Control building defaults, display preferences, and operational setup." buildings={buildingsQuery.data} buildingId={buildingId} onBuildingChange={setBuildingId} />
    <div className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><form onSubmit={submit} className="rounded-3xl border border-border/70 bg-card p-5 shadow-[0_10px_28px_rgba(23,43,77,0.05)] sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Settings2 className="h-5 w-5" /></div><div><h2 className="font-semibold">Building defaults</h2><p className="mt-1 text-sm text-muted-foreground">These values flow into new room and collection workflows.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Building name"><input required name="name" defaultValue={building.name} className={fieldClass} /></Field><Field label="City"><input name="city" defaultValue={building.city ?? ""} className={fieldClass} /></Field><div className="sm:col-span-2"><Field label="Address"><input required name="address" defaultValue={building.address} className={fieldClass} /></Field></div><Field label="Nearby landmark"><input name="landmark" defaultValue={building.landmark ?? ""} className={fieldClass} /></Field><Field label="Manager contact phone"><input type="tel" name="contactPhone" defaultValue={building.contactPhone ?? ""} className={fieldClass} /></Field><Field label="Property photo URL"><input type="url" name="imageUrl" defaultValue={building.imageUrl ?? ""} className={fieldClass} /></Field><Field label="Google Maps URL"><input type="url" name="mapUrl" defaultValue={building.mapUrl ?? ""} className={fieldClass} /></Field><Field label="Fixed monthly Owner cut (₹)"><input name="ownerMonthlyCut" type="number" min="0" step="0.01" inputMode="decimal" defaultValue={(building.ownerMonthlyCutPaise ?? 0) / 100} className={fieldClass} /></Field><Field label="Electricity rate per unit (₹)"><input required name="rate" inputMode="decimal" defaultValue={building.electricityRatePaise / 100} className={fieldClass} /></Field><Field label="Monthly rent due day"><input required name="rentDueDay" type="number" min="1" max="28" inputMode="numeric" defaultValue={building.rentDueDay} className={fieldClass} /></Field><div className="flex items-end"><span className="rounded-xl bg-muted px-3 py-2.5 text-xs text-muted-foreground">Current electricity: {formatCurrency(building.electricityRatePaise)} / unit</span></div></div><div className="mt-6"><PrimaryAction type="submit">{update.isPending ? "Saving…" : "Save building settings"}</PrimaryAction></div></form>
      <div className="space-y-5"><section className="rounded-3xl bg-[#123B38] p-5 text-white shadow-[0_16px_36px_rgba(18,59,56,0.22)]"><div className="flex items-start gap-3"><BellRing className="mt-0.5 h-5 w-5 text-[#BCE7D6]" /><div><h2 className="font-semibold">Daily collection maintenance</h2><p className="mt-2 text-sm leading-6 text-white/70">The managed daily schedule creates missing current-month rent cycles, refreshes Manager rent and electricity alerts, then notifies the Owner about newly overdue rent. It is retry-safe and never overwrites a recorded payment.</p></div></div></section><MotionPreferencePanel /><section className="rounded-3xl border border-border/70 bg-card p-5 shadow-[0_10px_28px_rgba(23,43,77,0.05)]"><div className="flex items-center gap-3"><LayoutList className="h-5 w-5 text-primary" /><div><h2 className="font-semibold">Manager data density</h2><p className="mt-1 text-sm text-muted-foreground">Choose how much space Manager tables and cards use on this device.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2" role="radiogroup" aria-label="Manager data density">{([{ value: "comfortable", label: "Comfortable", description: "More spacing for touch-friendly review." }, { value: "compact", label: "Compact", description: "Show more rows and cards on each screen." }] as const).map(option => { const selected = displayDensity === option.value; return <button key={option.value} type="button" role="radio" aria-checked={selected} onClick={() => setDisplayDensity(option.value)} className={`rounded-2xl border p-3 text-left transition ${selected ? "border-primary bg-primary/[0.05] text-primary" : "border-border bg-background text-foreground hover:border-primary/30"}`}><span className="block text-sm font-semibold">{option.label}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{option.description}</span></button>; })}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">Compact density affects Manager workspace cards and table rows only. This preference is saved on this device.</p></section><section className="rounded-3xl border border-border/70 bg-card p-5 shadow-[0_10px_28px_rgba(23,43,77,0.05)]"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-primary" /><div><h2 className="font-semibold">Role scope</h2><p className="mt-1 text-sm text-muted-foreground">Detailed team assignment is available under Team.</p></div></div><div className="mt-4 divide-y divide-border/70">{roles.map(([role, detail]) => <div key={role} className="py-3"><p className="text-sm font-semibold">{role}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>)}</div></section></div></div>
  </div>;
}
