import { Archive, BedDouble, ContactRound, DoorOpen, FileText, KeyRound, LogOut, Pencil, Search, Trash2, UserPlus } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { BuildingEmptyState, LoadingState } from "@/components/AppStates";
import { PageHeader, PrimaryAction } from "@/components/PageHeader";
import { formatCurrency, formatDate, toPaise } from "@/lib/format";
import { buildTenantAccessMessage } from "@shared/sharing";
import { trpc } from "@/lib/trpc";
import { useActiveBuilding } from "@/hooks/useActiveBuilding";
import { useDeletionSafety } from "@/components/DeletionSafety";

const fieldClass = "h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10";
const roomTypeFilterOptions = [
  { value: "all", label: "All" },
  { value: "single", label: "Single" },
  { value: "double", label: "Double sharing" },
  { value: "triple", label: "Triple sharing" },
  { value: "four", label: "Four sharing" },
  { value: "individual", label: "Individual room" },
  { value: "coliving", label: "Co-living" },
] as const;
type RoomTypeFilter = typeof roomTypeFilterOptions[number]["value"];

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block text-sm font-medium"><span className="mb-1.5 block">{label}</span>{children}</label>;
}

function TransferProrationPreview({ sourceMonthlyRentPaise, destinationMonthlyRentRupees, effectiveDate, enabled }: { sourceMonthlyRentPaise: number; destinationMonthlyRentRupees: string; effectiveDate: string; enabled: boolean }) {
  if (!enabled) return null;
  const destinationMonthlyRentPaise = toPaise(destinationMonthlyRentRupees);
  const date = /^\d{4}-(0[1-9]|1[0-2])-\d{2}$/.test(effectiveDate) ? new Date(`${effectiveDate}T00:00:00.000Z`) : null;
  if (!date || Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== effectiveDate || destinationMonthlyRentPaise <= 0) return <p className="rounded-xl border border-amber-200 bg-amber-50 p-2.5 text-xs leading-5 text-amber-900">Enter a valid transfer date and new monthly rent to preview the adjustment.</p>;
  const daysInMonth = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 0)).getUTCDate();
  const sourceDays = date.getUTCDate() - 1;
  const destinationDays = daysInMonth - sourceDays;
  if (sourceDays < 1) return <p className="rounded-xl border border-amber-200 bg-amber-50 p-2.5 text-xs leading-5 text-amber-900">Proration is not needed on the first day of the month; the destination room uses its regular monthly rent cycle.</p>;
  const sourceAmountPaise = Math.round((sourceMonthlyRentPaise * sourceDays) / daysInMonth);
  const destinationAmountPaise = Math.round((destinationMonthlyRentPaise * destinationDays) / daysInMonth);
  return <div className="rounded-xl border border-primary/20 bg-primary/[0.035] p-3 text-xs" aria-live="polite"><p className="font-semibold text-foreground">Live proration preview</p><div className="mt-2 grid grid-cols-2 gap-2"><div><p className="text-muted-foreground">Source room · {sourceDays}/{daysInMonth} days</p><p className="mt-0.5 font-semibold">{formatCurrency(sourceAmountPaise)}</p></div><div><p className="text-muted-foreground">Destination · {destinationDays}/{daysInMonth} days</p><p className="mt-0.5 font-semibold">{formatCurrency(destinationAmountPaise)}</p></div></div><p className="mt-2 leading-5 text-muted-foreground">Amounts are calculated in paise and are applied only if the source month has not received any payment.</p></div>;
}

export default function Tenants() {
  const { buildingsQuery, building, buildingId, setBuildingId, snapshotQuery: snapshot } = useActiveBuilding();
  const utils = trpc.useUtils();
  const { requestDelete } = useDeletionSafety();
  const [showAdd, setShowAdd] = useState(false);
  const [showAllocation, setShowAllocation] = useState(false);
  const [allocationTenantId, setAllocationTenantId] = useState<number | null>(null);
  const [showService, setShowService] = useState(false);
  const [editingTenantId, setEditingTenantId] = useState<number | null>(null);
  const tenantEditRef = useRef<HTMLFormElement>(null);
  const [vacatingAllocationId, setVacatingAllocationId] = useState<number | null>(null);
  const [transferringAllocationId, setTransferringAllocationId] = useState<number | null>(null);
  const [transferDrafts, setTransferDrafts] = useState<Record<number, { effectiveDate: string; monthlyRent: string; applyProration: boolean }>>({});
  const [offboardingTenantId, setOffboardingTenantId] = useState<number | null>(null);
  const [roomTypeFilter, setRoomTypeFilter] = useState<RoomTypeFilter>("all");
  const [tenantSearch, setTenantSearch] = useState("");
  useEffect(() => {
    if (!editingTenantId) return;
    const frame = window.requestAnimationFrame(() => tenantEditRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }));
    return () => window.cancelAnimationFrame(frame);
  }, [editingTenantId]);

  const refresh = async () => { await utils.pg.operations.snapshot.invalidate(); await utils.pg.dashboard.get.invalidate(); };
  const createTenant = trpc.pg.operations.createTenant.useMutation({ onSuccess: async () => { await refresh(); setShowAdd(false); toast.success("Tenant profile and login created"); }, onError: error => toast.error(error.message) });
  const updateTenant = trpc.pg.operations.updateTenant.useMutation({ onError: error => toast.error(error.message) });
  const resetTenantCredentials = trpc.pg.operations.resetTenantCredentials.useMutation({ onSuccess: () => toast.success("Tenant login password reset"), onError: error => toast.error(error.message) });
  const allocate = trpc.pg.operations.allocateTenant.useMutation({ onSuccess: async () => { await refresh(); setShowAllocation(false); toast.success("Tenant allocated to room"); }, onError: error => toast.error(error.message) });
  const updateAllocation = trpc.pg.operations.updateAllocation.useMutation({ onError: error => toast.error(error.message) });
  const vacate = trpc.pg.operations.vacateTenant.useMutation({ onSuccess: async () => { await refresh(); setVacatingAllocationId(null); toast.success("Move-out recorded and bed released"); }, onError: error => toast.error(error.message) });
  const transferTenant = trpc.pg.operations.transferTenant.useMutation({ onSuccess: async () => { await refresh(); setTransferringAllocationId(null); toast.success("Tenant moved to the new room"); }, onError: error => toast.error(error.message) });
  const revokeCredentials = trpc.pg.operations.revokeTenantCredentials.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const archiveTenant = trpc.pg.operations.archiveTenant.useMutation({ onSuccess: async () => { await refresh(); setOffboardingTenantId(null); toast.success("Tenant offboarded; history preserved"); }, onError: error => toast.error(error.message) });
  const deleteTenant = trpc.pg.operations.deleteTenant.useMutation({ onSuccess: async () => { await refresh(); toast.success("Tenant profile deleted"); }, onError: error => toast.error(error.message) });
  const createTenantService = trpc.pg.operations.createTenantService.useMutation({ onSuccess: async () => { await refresh(); setShowService(false); toast.success("Tenant service added"); }, onError: error => toast.error(error.message) });
  const deleteTenantService = trpc.pg.operations.deleteTenantService.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });

  const roomOccupancy = useMemo(() => {
    const counts = new Map<number, number>();
    snapshot.data?.allocations.filter(item => item.status === "active").forEach(item => counts.set(item.roomId, (counts.get(item.roomId) ?? 0) + 1));
    return counts;
  }, [snapshot.data]);
  const unallocatedActiveTenants = useMemo(() => snapshot.data?.tenants.filter(tenant => tenant.status === "active" && !snapshot.data?.allocations.some(allocation => allocation.tenantId === tenant.id && allocation.status === "active")) ?? [], [snapshot.data]);

  const visibleTenants = useMemo(() => {
    if (!snapshot.data) return [];
    const normalizedSearch = tenantSearch.trim().toLocaleLowerCase();
    return snapshot.data.tenants.filter(tenant => {
      const allocation = snapshot.data.allocations.find(item => item.tenantId === tenant.id && item.status === "active");
      const room = snapshot.data.rooms.find(item => item.id === allocation?.roomId);
      const matchesRoomType = roomTypeFilter === "all" || room?.roomType === roomTypeFilter;
      const matchesSearch = normalizedSearch.length === 0 || tenant.fullName.toLocaleLowerCase().includes(normalizedSearch) || tenant.phone.toLocaleLowerCase().includes(normalizedSearch) || room?.number.toLocaleLowerCase().includes(normalizedSearch) === true;
      return matchesRoomType && matchesSearch;
    });
  }, [roomTypeFilter, snapshot.data, tenantSearch]);

  if (buildingsQuery.isLoading) return <LoadingState />;
  if (!building || !buildingId) return <BuildingEmptyState />;
  if (snapshot.isLoading || !snapshot.data) return <LoadingState />;

  const editingTenant = snapshot.data.tenants.find(tenant => tenant.id === editingTenantId);
  const editingAllocation = snapshot.data.allocations.find(allocation => allocation.tenantId === editingTenantId && allocation.status === "active");
  const submitTenant = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    createTenant.mutate({ buildingId, fullName: String(form.get("fullName")), phone: String(form.get("phone")), password: String(form.get("password")), email: String(form.get("email")), identityDocumentUrl: String(form.get("identityDocumentUrl")) || undefined, emergencyContactName: String(form.get("emergencyName")) || undefined, emergencyContactPhone: String(form.get("emergencyPhone")) || undefined, address: String(form.get("address")) || undefined });
  };
  const submitEdit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!editingTenant) return;
    const form = new FormData(event.currentTarget);
    try {
      await updateTenant.mutateAsync({ id: editingTenant.id, buildingId, fullName: String(form.get("fullName")), phone: String(form.get("phone")), email: String(form.get("email")), identityDocumentUrl: String(form.get("identityDocumentUrl")) || undefined, emergencyContactName: String(form.get("emergencyName")) || undefined, emergencyContactPhone: String(form.get("emergencyPhone")) || undefined, address: String(form.get("address")) || undefined, status: String(form.get("status")) as "active" | "inactive" });
      if (editingAllocation) await updateAllocation.mutateAsync({ id: editingAllocation.id, buildingId, moveInDate: String(form.get("moveInDate")), bedLabel: String(form.get("bedLabel")) || undefined, monthlyRentPaise: toPaise(String(form.get("monthlyRent"))), depositPaise: toPaise(String(form.get("deposit"))) });
      await refresh();
      setEditingTenantId(null);
      toast.success("Tenant details updated");
    } catch { /* mutation error toast is handled by the corresponding mutation */ }
  };
  const shareTenantAccess = async (tenant: NonNullable<typeof snapshot.data>["tenants"][number]) => {
    const message = buildTenantAccessMessage(building, tenant.fullName);
    try { if (navigator.share) await navigator.share({ title: `${building.name} resident access`, text: message }); else { await navigator.clipboard.writeText(message); toast.success("Tenant access message copied"); } } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) toast.error("Unable to share tenant access"); }
  };

return <div className="pb-8">
    {snapshot.data.tenants.length > 0 ? <section className="mb-5 rounded-3xl border border-primary/20 bg-primary/[0.035] p-4"><h2 className="text-sm font-semibold">Resident access sharing</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Share a safe sign-in message after giving the tenant their password separately. Passwords are never included in the shared message.</p><div className="mt-3 flex flex-wrap gap-2">{snapshot.data.tenants.filter(tenant => tenant.status === "active").map(tenant => <button key={tenant.id} type="button" onClick={() => shareTenantAccess(tenant)} className="h-9 rounded-xl border border-primary/20 bg-card px-3 text-xs font-semibold text-primary">Share access for {tenant.fullName}</button>)}</div></section> : null}
    <PageHeader eyebrow="Residents" title="Tenants & allocation" description="Create logins, correct profile details, allocate rooms, manage tiffin or water services, and offboard without losing rent history." buildings={buildingsQuery.data} buildingId={buildingId} onBuildingChange={setBuildingId} actions={<><button onClick={() => { setAllocationTenantId(null); setShowAllocation(value => !value); }} disabled={unallocatedActiveTenants.length === 0} className="h-10 rounded-xl border border-border bg-card px-3 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50"><BedDouble className="mr-1.5 inline h-4 w-4 text-primary" />Allocate</button><button onClick={() => setShowService(value => !value)} className="h-10 rounded-xl border border-border bg-card px-3 text-sm font-semibold">Add service</button><PrimaryAction onClick={() => setShowAdd(value => !value)}><UserPlus className="mr-1.5 h-4 w-4" />Add tenant</PrimaryAction></>} />
    {showAdd ? <form onSubmit={submitTenant} className="mb-5 grid gap-3 rounded-3xl border border-primary/20 bg-primary/[0.035] p-4 sm:grid-cols-2 sm:p-5"><Field label="Full name"><input required name="fullName" className={fieldClass} /></Field><Field label="Mobile number"><input required name="phone" inputMode="tel" className={fieldClass} /></Field><Field label="Tenant login password"><input required name="password" type="password" minLength={8} className={fieldClass} /></Field><Field label="Identity document URL"><input name="identityDocumentUrl" type="url" className={fieldClass} placeholder="https://…" /></Field><Field label="Email"><input name="email" type="email" className={fieldClass} /></Field><Field label="Emergency contact name"><input name="emergencyName" className={fieldClass} /></Field><Field label="Emergency contact number"><input name="emergencyPhone" inputMode="tel" className={fieldClass} /></Field><Field label="Home address"><input name="address" className={fieldClass} /></Field><div className="sm:col-span-2"><PrimaryAction type="submit">{createTenant.isPending ? "Saving…" : "Create tenant"}</PrimaryAction></div></form> : null}
    {showAllocation ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); allocate.mutate({ buildingId, tenantId: Number(form.get("tenantId")), roomId: Number(form.get("roomId")), moveInDate: String(form.get("moveInDate")), bedLabel: String(form.get("bedLabel")) || undefined, monthlyRentPaise: toPaise(String(form.get("monthlyRent"))), depositPaise: toPaise(String(form.get("deposit"))) }); }} className="mb-5 grid gap-3 rounded-3xl border border-primary/20 bg-primary/[0.035] p-4 sm:grid-cols-2 sm:p-5"><div className="sm:col-span-2 rounded-2xl border border-primary/15 bg-card/70 p-3 text-xs leading-5 text-muted-foreground">Only active tenants without a current room are listed. Enter this tenant’s agreed monthly rent; shared-room totals are derived from each active tenant’s rent.</div><Field label="Tenant"><select required name="tenantId" value={allocationTenantId ?? ""} onChange={event => setAllocationTenantId(Number(event.target.value) || null)} className={fieldClass}><option value="">Choose unallocated tenant</option>{unallocatedActiveTenants.map(tenant => <option key={tenant.id} value={tenant.id}>{tenant.fullName}</option>)}</select></Field><Field label="Room"><select required name="roomId" className={fieldClass}><option value="">Choose room</option>{snapshot.data.rooms.filter(room => (roomOccupancy.get(room.id) ?? 0) < room.capacity).map(room => <option key={room.id} value={room.id}>Room {room.number} · {room.airConditioning === "ac" ? "AC" : "Non-AC"} · {room.capacity - (roomOccupancy.get(room.id) ?? 0)} bed(s) open</option>)}</select></Field><Field label="Move-in date"><input required name="moveInDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className={fieldClass} /></Field><Field label="Bed label"><input name="bedLabel" className={fieldClass} /></Field><Field label="Tenant monthly rent (₹)"><input required name="monthlyRent" inputMode="decimal" className={fieldClass} /></Field><Field label="Deposit (₹)"><input required name="deposit" inputMode="decimal" defaultValue="0" className={fieldClass} /></Field><div className="sm:col-span-2 flex gap-2"><PrimaryAction type="submit">{allocate.isPending ? "Allocating…" : "Confirm allocation"}</PrimaryAction><button type="button" onClick={() => setShowAllocation(false)} className="h-10 rounded-xl border border-border bg-card px-3 text-sm font-semibold">Cancel</button></div></form> : null}
    {showService ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createTenantService.mutate({ buildingId, tenantId: Number(form.get("tenantId")), serviceType: String(form.get("serviceType")) as "tiffin" | "water_bottle" | "other", monthlyChargePaise: toPaise(String(form.get("monthlyCharge"))), notes: String(form.get("notes")) || undefined }); }} className="mb-5 grid gap-3 rounded-3xl border border-emerald-200 bg-emerald-50/60 p-4 sm:grid-cols-2 sm:p-5"><Field label="Tenant"><select required name="tenantId" className={fieldClass}><option value="">Choose tenant</option>{snapshot.data.tenants.filter(tenant => tenant.status === "active").map(tenant => <option key={tenant.id} value={tenant.id}>{tenant.fullName}</option>)}</select></Field><Field label="Service"><select name="serviceType" className={fieldClass}><option value="tiffin">Tiffin</option><option value="water_bottle">Water bottle</option><option value="other">Other</option></select></Field><Field label="Monthly charge (₹)"><input required name="monthlyCharge" inputMode="decimal" className={fieldClass} /></Field><Field label="Notes"><input name="notes" className={fieldClass} placeholder="Plan, quantity, vendor" /></Field><div className="sm:col-span-2"><PrimaryAction type="submit">{createTenantService.isPending ? "Saving…" : "Save tenant service"}</PrimaryAction></div></form> : null}
    <section className="mb-5 overflow-hidden rounded-3xl border border-emerald-200 bg-card"><div className="border-b border-emerald-100 px-5 py-4"><h2 className="text-sm font-semibold">Tenant tiffin & water services</h2><p className="mt-1 text-xs text-muted-foreground">Active monthly services contribute to the selected building's projected result.</p></div><div className="divide-y divide-border/70">{snapshot.data.tenantServices.length === 0 ? <p className="p-5 text-sm text-muted-foreground">No tenant-level services configured.</p> : snapshot.data.tenantServices.map(service => { const tenant = snapshot.data.tenants.find(item => item.id === service.tenantId); return <div key={service.id} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="text-sm font-semibold">{tenant?.fullName ?? "Tenant"} · {service.serviceType.replace("_", " ")}</p><p className="mt-1 text-xs text-muted-foreground">{service.active} · {service.notes ?? "No notes"}</p></div><div className="flex items-center gap-2"><span className="text-sm font-semibold">{formatCurrency(service.monthlyChargePaise)}</span><button type="button" onClick={() => requestDelete({ label: `${tenant?.fullName ?? "Tenant"} service`, description: "This removes the selected tenant service from future charges. Existing billed and paid history remains protected.", onConfirm: () => deleteTenantService.mutate({ id: service.id, buildingId, tenantId: service.tenantId }) })} className="h-8 rounded-lg border border-rose-200 px-2 text-xs font-semibold text-rose-700">Remove</button></div></div>; })}</div></section>
    {editingTenant ? <form ref={tenantEditRef} onSubmit={submitEdit} className="mb-5 grid gap-3 rounded-3xl border border-primary/20 bg-primary/[0.035] p-4 sm:grid-cols-2 sm:p-5"><Field label="Status"><select name="status" defaultValue={editingTenant.status} className={fieldClass}><option value="active">Active</option><option value="inactive">Inactive</option></select></Field><Field label="Full name"><input required name="fullName" defaultValue={editingTenant.fullName} className={fieldClass} /></Field><Field label="Mobile number"><input required name="phone" defaultValue={editingTenant.phone} inputMode="tel" className={fieldClass} /></Field><Field label="Email"><input name="email" type="email" defaultValue={editingTenant.email ?? ""} className={fieldClass} /></Field><Field label="Identity document URL"><input name="identityDocumentUrl" type="url" defaultValue={editingTenant.identityDocumentUrl ?? ""} className={fieldClass} /></Field><Field label="Emergency contact name"><input name="emergencyName" defaultValue={editingTenant.emergencyContactName ?? ""} className={fieldClass} /></Field><Field label="Emergency contact number"><input name="emergencyPhone" defaultValue={editingTenant.emergencyContactPhone ?? ""} className={fieldClass} /></Field><Field label="Home address"><input name="address" defaultValue={editingTenant.address ?? ""} className={fieldClass} /></Field>{editingAllocation ? <><Field label="Move-in date"><input name="moveInDate" type="date" defaultValue={editingAllocation.moveInDate} className={fieldClass} /></Field><Field label="Bed label"><input name="bedLabel" defaultValue={editingAllocation.bedLabel ?? ""} className={fieldClass} /></Field><Field label="Monthly rent (₹)"><input required name="monthlyRent" inputMode="decimal" defaultValue={editingAllocation.monthlyRentPaise / 100} className={fieldClass} /></Field><Field label="Deposit (₹)"><input required name="deposit" inputMode="decimal" defaultValue={editingAllocation.depositPaise / 100} className={fieldClass} /></Field></> : null}<div className="sm:col-span-2 flex gap-2"><PrimaryAction type="submit">{updateTenant.isPending || updateAllocation.isPending ? "Saving…" : "Save tenant details"}</PrimaryAction><button type="button" onClick={() => setEditingTenantId(null)} className="h-10 rounded-xl border border-border bg-card px-3 text-sm font-semibold">Cancel</button></div></form> : null}
    {editingTenant ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); resetTenantCredentials.mutate({ tenantId: editingTenant.id, buildingId, password: String(form.get("newPassword")) }); }} className="mb-5 flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50/60 p-4 sm:flex-row sm:items-end"><Field label="Reset tenant login password"><input required name="newPassword" type="password" minLength={8} autoComplete="new-password" className={fieldClass} placeholder="Minimum 8 characters" /></Field><button type="submit" disabled={resetTenantCredentials.isPending} className="h-10 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-60">{resetTenantCredentials.isPending ? "Resetting…" : "Reset login password"}</button></form> : null}
    <section className="mb-4 rounded-2xl border border-border/70 bg-card p-3 shadow-[0_8px_20px_rgba(23,43,77,0.04)]">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div><p className="text-sm font-semibold">Filter by room type</p><p className="text-xs text-muted-foreground">{visibleTenants.length} of {snapshot.data.tenants.length} tenant{snapshot.data.tenants.length === 1 ? "" : "s"} shown</p></div>
        <div className="mobile-scroll-controls flex gap-2" role="group" aria-label="Filter tenants by room type">
          {roomTypeFilterOptions.map(option => <button key={option.value} type="button" onClick={() => setRoomTypeFilter(option.value)} className={`h-9 rounded-xl px-3 text-xs font-semibold transition ${roomTypeFilter === option.value ? "bg-primary text-primary-foreground" : "border border-border bg-background text-foreground hover:bg-muted"}`}>{option.label}</button>)}
        </div>
      </div>
      <label className="relative mt-3 block"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={tenantSearch} onChange={event => setTenantSearch(event.target.value)} className="h-11 w-full rounded-xl border border-border bg-background pl-10 pr-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="Search tenant, room number, or phone" aria-label="Search tenants by name, room number, or phone" /></label>
    </section>
    <section className="motion-stagger grid gap-3 md:grid-cols-2 xl:grid-cols-3">
      {snapshot.data.tenants.length === 0 ? <div className="md:col-span-2 xl:col-span-3 rounded-3xl border border-dashed border-border bg-muted/30 p-8 text-center"><ContactRound className="mx-auto h-6 w-6 text-primary" /><p className="mt-3 font-semibold">No tenant profiles yet</p><p className="mt-1 text-sm text-muted-foreground">Create a tenant profile, then assign that tenant to an available bed.</p></div> : visibleTenants.length === 0 ? <div className="md:col-span-2 xl:col-span-3 rounded-3xl border border-dashed border-border bg-muted/30 p-8 text-center"><ContactRound className="mx-auto h-6 w-6 text-primary" /><p className="mt-3 font-semibold">No tenants in this room type</p><p className="mt-1 text-sm text-muted-foreground">Choose another room-type filter to see allocated tenants.</p></div> : visibleTenants.map(tenant => {
        const allocation = snapshot.data.allocations.find(item => item.tenantId === tenant.id && item.status === "active");
        const room = snapshot.data.rooms.find(item => item.id === allocation?.roomId);
        const transferDraft = allocation ? transferDrafts[allocation.id] ?? { effectiveDate: new Date().toISOString().slice(0, 10), monthlyRent: String(allocation.monthlyRentPaise / 100), applyProration: false } : null;
        const updateTransferDraft = (changes: Partial<NonNullable<typeof transferDraft>>) => { if (allocation) setTransferDrafts(current => ({ ...current, [allocation.id]: { ...(current[allocation.id] ?? { effectiveDate: new Date().toISOString().slice(0, 10), monthlyRent: String(allocation.monthlyRentPaise / 100), applyProration: false }), ...changes } })); };
        const transferHistory = snapshot.data.tenantTransfers.filter(transfer => transfer.tenantId === tenant.id);
        return <article key={tenant.id} className="interactive-surface rounded-3xl border border-border/70 bg-card p-5 shadow-[0_10px_28px_rgba(23,43,77,0.05)]">
          <div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10 text-sm font-semibold text-primary">{tenant.fullName.slice(0, 1).toUpperCase()}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${allocation ? "bg-emerald-50 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{allocation ? "Allocated" : "Unallocated"}</span></div>
          <h2 className="mt-4 text-base font-semibold">{tenant.fullName}</h2><p className="mt-1 text-sm text-muted-foreground">{tenant.phone}</p>
          <div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => setEditingTenantId(tenant.id)} className="inline-flex h-8 items-center gap-1 rounded-lg border border-border px-2.5 text-xs font-semibold"><Pencil className="h-3.5 w-3.5" />Edit</button>{tenant.identityDocumentUrl ? <a href={tenant.identityDocumentUrl} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center gap-1 rounded-lg border border-sky-200 px-2.5 text-xs font-semibold text-sky-700"><FileText className="h-3.5 w-3.5" />Document</a> : null}{tenant.status === "active" && tenant.userId ? <button type="button" onClick={() => requestDelete({ label: `${tenant.fullName} login access`, description: "This removes the tenant’s sign-in access. Their operational history remains available to the Manager.", onConfirm: () => revokeCredentials.mutate({ tenantId: tenant.id, buildingId }) })} className="inline-flex h-8 items-center gap-1 rounded-lg border border-rose-200 px-2.5 text-xs font-semibold text-rose-700"><KeyRound className="h-3.5 w-3.5" />Revoke login</button> : null}<button type="button" onClick={() => setOffboardingTenantId(tenant.id)} className="inline-flex h-8 items-center gap-1 rounded-lg border border-amber-200 px-2.5 text-xs font-semibold text-amber-800"><Archive className="h-3.5 w-3.5" />Offboard</button><button type="button" onClick={() => requestDelete({ label: `${tenant.fullName} profile`, description: "Profiles with allocations, bills, or payment history are protected. Only a history-free profile can be removed.", onConfirm: () => deleteTenant.mutate({ tenantId: tenant.id, buildingId }) })} className="inline-flex h-8 items-center gap-1 rounded-lg border border-rose-200 px-2.5 text-xs font-semibold text-rose-700"><Trash2 className="h-3.5 w-3.5" />Delete</button></div>
          {offboardingTenantId === tenant.id ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); archiveTenant.mutate({ tenantId: tenant.id, buildingId, moveOutDate: String(form.get("moveOutDate")) }); }} className="mt-4 grid gap-2 rounded-2xl border border-amber-200 bg-amber-50/60 p-3"><p className="text-xs font-semibold text-amber-900">Offboarding vacates active beds, revokes login, and preserves records.</p><input required name="moveOutDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className={fieldClass} /><div className="flex gap-2"><button type="submit" className="h-9 rounded-lg bg-amber-700 px-3 text-xs font-semibold text-white">{archiveTenant.isPending ? "Saving…" : "Confirm offboard"}</button><button type="button" onClick={() => setOffboardingTenantId(null)} className="h-9 rounded-lg border border-border bg-card px-3 text-xs font-semibold">Cancel</button></div></form> : null}
          {allocation && room ? <div className="mt-4 rounded-2xl bg-muted/60 p-3">
            <p className="flex items-center gap-1 text-xs font-medium text-muted-foreground"><DoorOpen className="h-3.5 w-3.5 text-primary" />Room {room.number} · {room.roomType === "four" ? "Four sharing" : `${room.roomType[0].toUpperCase()}${room.roomType.slice(1)}${room.roomType === "single" ? "" : " sharing"}`} · {room.airConditioning === "ac" ? "AC" : "Non-AC"}{allocation.bedLabel ? ` · Bed ${allocation.bedLabel}` : ""}</p>
            <p className="mt-2 text-sm font-semibold">{formatCurrency(allocation.monthlyRentPaise)} / month</p>
            <div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => setTransferringAllocationId(value => value === allocation.id ? null : allocation.id)} className="inline-flex h-8 items-center gap-1 rounded-lg border border-primary/25 bg-primary/[0.04] px-2.5 text-xs font-semibold text-primary"><BedDouble className="h-3.5 w-3.5" />Transfer room</button><button type="button" onClick={() => setVacatingAllocationId(allocation.id)} className="inline-flex h-8 items-center gap-1 rounded-lg border border-border bg-card px-2.5 text-xs font-semibold"><LogOut className="h-3.5 w-3.5" />Record move-out</button></div>
            {transferringAllocationId === allocation.id && transferDraft ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); transferTenant.mutate({ buildingId, allocationId: allocation.id, destinationRoomId: Number(form.get("destinationRoomId")), effectiveDate: transferDraft.effectiveDate, bedLabel: String(form.get("bedLabel")) || undefined, monthlyRentPaise: toPaise(transferDraft.monthlyRent), depositPaise: toPaise(String(form.get("deposit"))), applyProration: transferDraft.applyProration }); }} className="mt-3 grid gap-2 rounded-xl border border-primary/20 bg-card p-3">
              <p className="text-xs leading-5 text-muted-foreground">This preserves the current allocation and payment history, releases the source bed, and starts a new active allocation in the destination room.</p>
              <label className="flex gap-2 rounded-xl border border-primary/15 bg-primary/[0.035] p-2.5 text-xs leading-5 text-slate-700"><input name="applyProration" type="checkbox" checked={transferDraft.applyProration} onChange={event => updateTransferDraft({ applyProration: event.target.checked })} className="mt-0.5 h-4 w-4 accent-primary" /><span><strong className="text-foreground">Automatically prorate this month’s rent.</strong> The system uses the transfer date to reduce the unpaid source rent and create an unpaid destination rent for the remaining days. It never changes collected rent or historical payments.</span></label>
              <TransferProrationPreview sourceMonthlyRentPaise={allocation.monthlyRentPaise} destinationMonthlyRentRupees={transferDraft.monthlyRent} effectiveDate={transferDraft.effectiveDate} enabled={transferDraft.applyProration} />
              <Field label="Destination room"><select required name="destinationRoomId" className={fieldClass}><option value="">Choose room with an open bed</option>{snapshot.data.rooms.filter(destination => destination.id !== room.id && (roomOccupancy.get(destination.id) ?? 0) < destination.capacity).map(destination => <option key={destination.id} value={destination.id}>Room {destination.number} · {destination.capacity - (roomOccupancy.get(destination.id) ?? 0)} bed(s) open</option>)}</select></Field>
              <Field label="Transfer date"><input required name="effectiveDate" type="date" value={transferDraft.effectiveDate} onChange={event => updateTransferDraft({ effectiveDate: event.target.value })} className={fieldClass} /></Field>
              <Field label="New bed label"><input name="bedLabel" defaultValue={allocation.bedLabel ?? ""} className={fieldClass} /></Field>
              <Field label="New monthly rent (₹)"><input required name="monthlyRent" inputMode="decimal" value={transferDraft.monthlyRent} onChange={event => updateTransferDraft({ monthlyRent: event.target.value })} className={fieldClass} /></Field>
              <Field label="Deposit carried forward (₹)"><input required name="deposit" inputMode="decimal" defaultValue={allocation.depositPaise / 100} className={fieldClass} /></Field>
              <div className="flex gap-2"><button type="submit" disabled={transferTenant.isPending} className="h-9 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50">{transferTenant.isPending ? "Moving…" : "Confirm transfer"}</button><button type="button" onClick={() => setTransferringAllocationId(null)} className="h-9 rounded-lg border border-border bg-card px-3 text-xs font-semibold">Cancel</button></div>
            </form> : null}
            {vacatingAllocationId === allocation.id ? <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); vacate.mutate({ buildingId, allocationId: allocation.id, moveOutDate: String(form.get("moveOutDate")) }); }} className="mt-3 grid gap-2"><input required name="moveOutDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className={fieldClass} /><div className="flex gap-2"><button type="submit" className="h-9 rounded-lg bg-rose-600 px-3 text-xs font-semibold text-white">{vacate.isPending ? "Saving…" : "Confirm move-out"}</button><button type="button" onClick={() => setVacatingAllocationId(null)} className="h-9 rounded-lg border border-border bg-card px-3 text-xs font-semibold">Cancel</button></div></form> : null}
          </div> : null}
          {transferHistory.length > 0 ? <section className="mt-4 rounded-2xl border border-primary/15 bg-primary/[0.025] p-3"><div><p className="text-sm font-semibold">Room transfer history</p><p className="mt-0.5 text-xs text-muted-foreground">Past room moves and recorded rent adjustments.</p></div><ol className="mt-3 space-y-3 border-l-2 border-primary/20 pl-3">{transferHistory.map(transfer => { const sourceRoom = snapshot.data.rooms.find(item => item.id === transfer.sourceRoomId); const destinationRoom = snapshot.data.rooms.find(item => item.id === transfer.destinationRoomId); return <li key={transfer.id} className="relative rounded-xl border border-border/70 bg-card p-3 before:absolute before:-left-[1.1rem] before:top-4 before:h-2 before:w-2 before:rounded-full before:bg-primary"><div className="flex flex-wrap items-center justify-between gap-1"><p className="text-xs font-semibold">Room {sourceRoom?.number ?? "—"} → Room {destinationRoom?.number ?? "—"}</p><time className="text-xs text-muted-foreground">{formatDate(transfer.effectiveDate)}</time></div><p className="mt-1 text-xs text-muted-foreground">Monthly rent: {formatCurrency(transfer.sourceMonthlyRentPaise)} → {formatCurrency(transfer.destinationMonthlyRentPaise)}</p>{transfer.prorationApplied === "yes" ? <p className="mt-2 rounded-lg bg-primary/[0.05] px-2 py-1.5 text-xs leading-5 text-primary">Prorated adjustment: source {formatCurrency(transfer.sourceProratedAmountPaise ?? 0)} · destination {formatCurrency(transfer.destinationProratedAmountPaise ?? 0)}</p> : <p className="mt-2 text-xs text-muted-foreground">No mid-month rent adjustment was applied.</p>}</li>; })}</ol></section> : null}
        </article>;
      })}
    </section>
  </div>;
}
